blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://t.me/nekochat
    about: Please ask and answer questions here.
  - name: Official Telegram Channel
    url: https://t.me/nekoupdates
    about: Subscribe for notifications and releases.
